version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27018:27017"
    networks:
      - app-network
    restart: always

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./rule-engine-frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

networks:
  app-network:
    driver: bridge
